<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abc123" name="com.webtest.ranzhicase.CustomerManageTestCases" tests="52" failures="2" timestamp="18 Dec 2019 15:34:25 GMT" time="940.354" errors="2">
  <testcase name="test20" time="0.039" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test48" time="26.805" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test35" time="13.171" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test36" time="32.166" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test09" time="11.019" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test45" time="14.627" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test23" time="15.848" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test05" time="19.940" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test30" time="30.526" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test37" time="14.847" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="LoginFail" time="19.289" classname="com.webtest.ranzhicase.CustomerManageTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.webtest.ranzhicase.CustomerManageTestCases.LoginFail(CustomerManageTestCases.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- LoginFail -->
  <testcase name="test44" time="28.384" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test04" time="10.884" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test48" time="27.295" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test33" time="1.102" classname="com.webtest.ranzhicase.CustomerManageTestCases">
    <error type="org.openqa.selenium.ElementClickInterceptedException" message="Element &lt;a href=&quot;/ranzhi/www/oa/index.php?m=overtime&amp;f=edit&amp;id=7&quot;&gt; is not clickable at point (1261,154) because another element &lt;div id=&quot;ajaxModal&quot; class=&quot;modal modal-trigger  fade in&quot;&gt; obscures it
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:53&#039;
System info: host: &#039;ABC123&#039;, ip: &#039;192.168.43.176&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_73&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 220, moz:profile: C:\Users\DELL\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: a80013b8-2c8e-40d8-8fb6-4c1d3c0cbb49">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <a href="/ranzhi/www/oa/index.php?m=overtime&f=edit&id=7"> is not clickable at point (1261,154) because another element <div id="ajaxModal" class="modal modal-trigger  fade in"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ABC123', ip: '192.168.43.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 220, moz:profile: C:\Users\DELL\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: a80013b8-2c8e-40d8-8fb6-4c1d3c0cbb49
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at com.webtest.core.WebDriverEngine.click(WebDriverEngine.java:140)
	at com.webtest.ranzhicase.CustomerManageTestCases.test33(CustomerManageTestCases.java:386)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- test33 -->
  <testcase name="test03" time="2.052" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test40" time="16.038" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test29" time="22.085" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test43" time="14.187" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test47" time="27.179" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test26" time="26.547" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test10" time="14.258" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test27" time="14.402" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test48" time="26.365" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test07" time="27.100" classname="com.webtest.ranzhicase.CustomerManageTestCases">
    <error type="org.openqa.selenium.ElementNotInteractableException" message="Element &lt;input id=&quot;productName&quot; class=&quot;form-control&quot; name=&quot;productName&quot; type=&quot;text&quot;&gt; is not reachable by keyboard
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:53&#039;
System info: host: &#039;ABC123&#039;, ip: &#039;192.168.43.176&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_73&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 220, moz:profile: C:\Users\DELL\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: a80013b8-2c8e-40d8-8fb6-4c1d3c0cbb49">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: Element <input id="productName" class="form-control" name="productName" type="text"> is not reachable by keyboard
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ABC123', ip: '192.168.43.176', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 220, moz:profile: C:\Users\DELL\AppData\Local..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: a80013b8-2c8e-40d8-8fb6-4c1d3c0cbb49
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
	at com.webtest.core.WebDriverEngine.type(WebDriverEngine.java:127)
	at com.webtest.ranzhicase.CustomerManageTestCases.test07(CustomerManageTestCases.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- test07 -->
  <testcase name="test42" time="32.000" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test14" time="15.182" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test15" time="18.833" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test28" time="15.319" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test24" time="15.290" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test17" time="15.049" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test19" time="15.608" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test25" time="33.846" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test46" time="27.793" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test41" time="16.819" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test16" time="22.880" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test12" time="23.821" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test18" time="13.863" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test31" time="11.707" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test01" time="9.989" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test22" time="15.212" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test13" time="15.244" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test06" time="21.770" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test02" time="9.269" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test34" time="20.393" classname="com.webtest.ranzhicase.CustomerManageTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.webtest.ranzhicase.CustomerManageTestCases.test34(CustomerManageTestCases.java:400)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test34 -->
  <testcase name="test21" time="12.240" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test39" time="22.061" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test38" time="11.918" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test08" time="20.677" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="LoginSuccess" time="7.095" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test11" time="17.055" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
  <testcase name="test32" time="23.266" classname="com.webtest.ranzhicase.CustomerManageTestCases"/>
</testsuite> <!-- com.webtest.ranzhicase.CustomerManageTestCases -->
