<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="47" total="48" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34726" started-at="2019-12-10T11:49:40Z" finished-at="2019-12-10T11:50:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34726" started-at="2019-12-10T11:49:40Z" finished-at="2019-12-10T11:50:15Z">
      <class name="pa.team1">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:pa.team1@224edc67]" name="doBeforeClass" is-config="true" duration-ms="5144" started-at="2019-12-10T11:49:40Z" finished-at="2019-12-10T11:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="Login()[pri:0, instance:pa.team1@224edc67]" name="Login" is-config="true" duration-ms="7931" started-at="2019-12-10T11:49:45Z" finished-at="2019-12-10T11:49:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="testTeam48()[pri:0, instance:pa.team1@224edc67]" name="testTeam48" duration-ms="21629" started-at="2019-12-10T11:49:53Z" description="点击团队最右上方关闭按钮，整个模块关闭" finished-at="2019-12-10T11:50:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at pa.team1.testTeam48(team1.java:1008)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTeam48 -->
      </class> <!-- pa.team1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
